### ISSUE TITLE
Property "endpoints[*].backend[*].telemetry/opentelemetry.layers" not allowed

### ISSUE THREAD

**Issue by adigiorgi-clickup** [krakend/krakend-schema#51]
https://github.com/krakend/krakend-otel/pull/27 added support for the `telemetry/opentelemetry.layers` property in the individual `backend` configurations, but the schema doesn't allow it.

Schema version: v2.7

**Comment by alombarte** [comment]
@dhontecillas Please check https://www.krakend.io/schema/v2.7/telemetry/opentelemetry-backend.json vs https://github.com/krakend/krakend-otel/pull/27
